name: CI/CD Fullstack

on:
  push:
    branches:
      - main

jobs:
  build-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Back-end
        uses: docker/build-push-action@v4
        with:
          context: ./fullstack/Back
          file: ./fullstack/Back/Dockerfile
          push: true
          tags: rahmashelbayeh/moto-back:${{ github.run_id }}

  build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Front-end
        uses: docker/build-push-action@v4
        with:
          context: ./fullstack/front/Event
          file: ./fullstack/front/Event/Dockerfile
          push: true
          tags: rahmashelbayeh/moto-front:${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-back, build-front]
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Stopping old containers..."
            docker rm -f moto-back moto-front || true

            echo "Pulling latest images..."
            docker pull rahmashelbayeh/moto-back:${{ github.run_id }}
            docker pull rahmashelbayeh/moto-front:${{ github.run_id }}

            echo "Starting Front-end..."
            docker run -d --restart unless-stopped --network moto-net -p 80:80 --name moto-front rahmashelbayeh/moto-front:${{ github.run_id }}

            echo "Starting Back-end..."
            docker run -d --restart unless-stopped --network moto-net -p 5000:5000 --name moto-back rahmashelbayeh/moto-back:${{ github.run_id }}
