name: Fullstack CI/CD

on:
  push:
    branches:
      - main

env:
  BACK_IMAGE: rahmashelbayeh/moto-back
  FRONT_IMAGE: rahmashelbayeh/moto-front
  TAG: ${{ github.run_id }}

jobs:

  db_stage:
    name: Build Database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start MySQL DB
        run: |
          docker run -d \
            --name moto-db \
            -e MYSQL_ROOT_PASSWORD=rootpassword \
            -e MYSQL_DATABASE=MotoRideDB \
            -v ${{ github.workspace }}/db/init.sql:/docker-entrypoint-initdb.d/init.sql \
            -p 3306:3306 \
            mysql:8.0
          sleep 10  # انتظر DB لتصبح جاهزة

  front_stage:
    name: Build Front-end
    runs-on: ubuntu-latest
    needs: db_stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Front-end Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front              # مسار مجلد front صحيح
          file: ./front/Dockerfile
          push: true
          tags: ${{ env.FRONT_IMAGE }}:${{ env.TAG }}

  back_stage:
    name: Build Back-end
    runs-on: ubuntu-latest
    needs: front_stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Back-end Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Back                  # context يشمل كل ملفات Back
          file: ./Back/MotoRide/Dockerfile # Dockerfile داخل مجلد MotoRide
          push: true
          tags: ${{ env.BACK_IMAGE }}:${{ env.TAG }}

  deploy_stage:
    name: Deploy Fullstack
    runs-on: ubuntu-latest
    needs: back_stage
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Stopping old containers..."
            docker rm -f moto-back moto-front || true
            echo "Pulling latest images..."
            docker pull ${{ env.BACK_IMAGE }}:${{ env.TAG }}
            docker pull ${{ env.FRONT_IMAGE }}:${{ env.TAG }}
            echo "Starting Front-end..."
            docker run -d -p 8080:80 --name moto-front ${{ env.FRONT_IMAGE }}:${{ env.TAG }}
            echo "Starting Back-end..."
            docker run -d -p 5000:5000 --name moto-back ${{ env.BACK_IMAGE }}:${{ env.TAG }}
