name: Fullstack CI/CD

on:
  push:
    branches:
      - main

env:
  BACK_IMAGE: rahmashelbayeh/moto-back
  FRONT_IMAGE: rahmashelbayeh/moto-front
  TAG: ${{ github.run_id }}

jobs:

  # 1️⃣ Database Stage (CI)
  db_stage:
    name: Start Database (MySQL for CI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run MySQL container (test only)
        run: |
          docker run -d \
            --name moto-db \
            -e MYSQL_ROOT_PASSWORD=rootpassword \
            -e MYSQL_DATABASE=MotoRideDB \
            -p 3306:3306 \
            -v ${{ github.workspace }}/db/init.sql:/docker-entrypoint-initdb.d/init.sql \
            --health-cmd="mysqladmin ping -uroot -prootpassword" \
            --health-interval=10s \
            --health-retries=10 \
            mysql:8.0
          echo "Waiting for DB to be healthy..."
          sleep 30

  # 2️⃣ Front-end Stage
  front_stage:
    name: Build Front-end
    runs-on: ubuntu-latest
    needs: db_stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Front-end Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front/Events
          file: ./front/Events/Dockerfile
          push: true
          tags: ${{ env.FRONT_IMAGE }}:${{ env.TAG }}

  # 3️⃣ Back-end Stage
  back_stage:
    name: Build Back-end
    runs-on: ubuntu-latest
    needs: front_stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Back-end Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Back
          file: ./Back/Dockerfile
          push: true
          tags: ${{ env.BACK_IMAGE }}:${{ env.TAG }}

  # 4️⃣ Deploy Stage
  deploy_stage:
    name: Deploy Fullstack to Server
    runs-on: ubuntu-latest
    needs: back_stage
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Create network if not exists..."
            docker network inspect moto-net >/dev/null 2>&1 || docker network create moto-net

            echo "Stopping old containers..."
            docker rm -f moto-db moto-back moto-front || true

            echo "Starting Database..."
            docker run -d --restart unless-stopped \
              --network moto-net \
              --name moto-db \
              -e MYSQL_ROOT_PASSWORD=rootpassword \
              -e MYSQL_DATABASE=MotoRideDB \
              -p 3306:3306 \
              mysql:8.0

            echo "Pulling latest images..."
            docker pull ${{ env.FRONT_IMAGE }}:${{ env.TAG }}
            docker pull ${{ env.BACK_IMAGE }}:${{ env.TAG }}

            echo "Starting Front-end..."
            docker run -d --restart unless-stopped \
              --network moto-net \
              -p 80:80 \
              --name moto-front \
              ${{ env.FRONT_IMAGE }}:${{ env.TAG }}

            echo "Starting Back-end..."
            docker run -d --restart unless-stopped \
              --network moto-net \
              -e ASPNETCORE_URLS=http://0.0.0.0:5000 \
              -e ConnectionStrings__DefaultConnection="Server=moto-db;Port=3306;Database=MotoRideDB;User=root;Password=rootpassword;" \
              -p 5000:5000 \
              --name moto-back \
              ${{ env.BACK_IMAGE }}:${{ env.TAG }}
