name: Fullstack CI/CD (Split Stages)

on:
  push:
    branches: [ main ]

env:
  BACK_IMAGE: rahmashelbayeh/moto-back
  FRONT_IMAGE: rahmashelbayeh/moto-front
  TAG: ${{ github.run_id }}

jobs:

  front_stage:
    name: Build & Push Front-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push front image
        uses: docker/build-push-action@v5
        with:
          context: ./fullstack/front/Event
          file: ./fullstack/front/Event/Dockerfile
          push: true
          tags: |
            ${{ env.FRONT_IMAGE }}:${{ env.TAG }}

  back_stage:
    name: Build & Push Back-end
    runs-on: ubuntu-latest
    needs: front_stage
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push back image
        uses: docker/build-push-action@v5
        with:
          context: ./fullstack/Back
          file: ./fullstack/Back/Dockerfile
          push: true
          tags: |
            ${{ env.BACK_IMAGE }}:${{ env.TAG }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [front_stage, back_stage]
    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # شبكة مشتركة
            docker network inspect moto-net >/dev/null 2>&1 || docker network create moto-net

            echo "Stop old containers"
            docker rm -f moto-front moto-back || true

            echo "Pull latest images"
            docker pull ${{ env.FRONT_IMAGE }}:${{ env.TAG }}
            docker pull ${{ env.BACK_IMAGE }}:${{ env.TAG }}

            echo "Run FRONT on :80"
            docker run -d --restart unless-stopped \
              --network moto-net \
              -p 80:80 \
              --name moto-front \
              ${{ env.FRONT_IMAGE }}:${{ env.TAG }}

            echo "Run BACK on :5000"
            docker run -d --restart unless-stopped \
              --network moto-net \
              -e ASPNETCORE_URLS=http://0.0.0.0:5000 \
              -p 5000:5000 \
              --name moto-back \
              ${{ env.BACK_IMAGE }}:${{ env.TAG }}
